erDiagram
  accounts
  personal_api_keys
  pow_sessions
  browser_replay_events
  browser_sessions
  canned_responses
  companies
  conversations
  customers
  event_subscriptions
  files
  github_authorizations
  gmail_conversation_threads
  google_authorizations
  conversation_issues
  customer_issues
  issues
  lambdas
  mattermost_authorizations
  mattermost_conversation_threads
  mentions
  messages
  message_files
  notes
  slack_authorizations
  slack_conversation_threads
  conversation_tags
  customer_tags
  tags
  twilio_authorizations
  user_invitations
  users
  user_profiles
  user_settings
  widget_settings
  schema_migrations
  oban_jobs
  accounts ||--|{ browser_replay_events : ""
  accounts ||--|{ browser_sessions : ""
  accounts ||--|{ canned_responses : ""
  accounts ||--|{ companies : ""
  accounts ||--|{ conversation_issues : ""
  accounts ||--|{ conversation_tags : ""
  accounts ||--|{ conversations : ""
  accounts ||--|{ customer_issues : ""
  accounts ||--|{ customer_tags : ""
  accounts ||--|{ customers : ""
  accounts ||--|{ event_subscriptions : ""
  accounts ||--|{ files : ""
  accounts ||--|{ github_authorizations : ""
  accounts ||--|{ gmail_conversation_threads : ""
  accounts ||--|{ google_authorizations : ""
  accounts ||--|{ issues : ""
  accounts ||--|{ lambdas : ""
  accounts ||--|{ mattermost_authorizations : ""
  accounts ||--|{ mattermost_conversation_threads : ""
  accounts ||--|{ mentions : ""
  accounts ||--|{ message_files : ""
  accounts ||--|{ messages : ""
  accounts ||--|{ notes : ""
  accounts ||--|{ personal_api_keys : ""
  accounts ||--|{ slack_authorizations : ""
  accounts ||--|{ slack_conversation_threads : ""
  accounts ||--|{ tags : ""
  accounts ||--|{ twilio_authorizations : ""
  accounts ||--|{ user_invitations : ""
  accounts ||--|{ users : ""
  accounts ||--o| widget_settings : ""
  browser_sessions ||--|{ browser_replay_events : ""
  companies ||--|{ customers : ""
  conversations ||--|{ conversation_issues : ""
  conversations ||--|{ conversation_tags : ""
  conversations ||--|{ gmail_conversation_threads : ""
  conversations ||--|{ mattermost_conversation_threads : ""
  conversations ||--|{ mentions : ""
  conversations ||--|{ messages : ""
  conversations ||--|{ slack_conversation_threads : ""
  customers ||--|{ browser_sessions : ""
  customers ||--|{ conversations : ""
  customers ||--|{ customer_issues : ""
  customers ||--|{ customer_tags : ""
  customers ||--|{ files : ""
  customers ||--|{ messages : ""
  customers ||--|{ notes : ""
  files ||--|{ message_files : ""
  issues ||--|{ conversation_issues : ""
  issues ||--|{ customer_issues : ""
  messages ||--|{ mentions : ""
  messages ||--|{ message_files : ""
  tags ||--|{ conversation_tags : ""
  tags ||--|{ customer_tags : ""
  users ||--|{ conversation_issues : ""
  users ||--|{ conversation_tags : ""
  users ||--|{ conversations : ""
  users ||--|{ customer_issues : ""
  users ||--|{ customer_tags : ""
  users ||--|{ files : ""
  users ||--|{ github_authorizations : ""
  users ||--|{ google_authorizations : ""
  users ||--|{ issues : ""
  users ||--|{ issues : ""
  users ||--|{ lambdas : ""
  users ||--|{ mattermost_authorizations : ""
  users ||--|{ mentions : ""
  users ||--|{ messages : ""
  users ||--|{ notes : ""
  users ||--|{ personal_api_keys : ""
  users ||--|{ tags : ""
  users ||--|{ twilio_authorizations : ""
  users ||--o| user_profiles : ""
  users ||--o| user_settings : ""
