erDiagram
  schema_migrations {
    integer version PK
    timestamp inserted_at
  }
  fun_with_flags_toggles {
    integer id PK
    varchar flag_name
    varchar gate_type
    varchar target
    boolean enabled
  }
  oban_jobs {
    integer id PK
    varchar state
    varchar queue
    varchar worker
    jsonb args
    jsonb meta
    array tags
    array errors
    integer attempt
    array attempted_by
    integer max_attempts
    integer priority
    timestamp attempted_at
    timestamp cancelled_at
    timestamp completed_at
    timestamp discarded_at
    timestamp inserted_at
    timestamp scheduled_at
  }
  api_keys {
    integer id PK
    varchar name
    array scopes
    integer hourly_request_limit
    varchar key_hash
    varchar key_prefix
    integer user_id
    timestamp inserted_at
    timestamp updated_at
  }
  email_activation_codes {
    integer id PK
    varchar code
    timestamp issued_at
    integer user_id
  }
  invitations {
    integer id PK
    varchar invitation_id
    varchar email
    varchar role
    integer inviter_id
    integer site_id
    timestamp inserted_at
    timestamp updated_at
  }
  totp_recovery_codes {
    integer id PK
    varchar code_digest
    integer user_id
    timestamp inserted_at
  }
  users {
    integer id PK
    varchar email
    varchar password_hash
    varchar name
    timestamp last_seen
    date trial_expiry_date
    varchar theme
    boolean email_verified
    varchar previous_email
    date accept_traffic_until
    boolean allow_next_upgrade_override
    boolean totp_enabled
    bytea totp_secret
    varchar totp_token
    timestamp totp_last_used_at
    jsonb grace_period
    timestamp inserted_at
    timestamp updated_at
  }
  enterprise_plans {
    integer id PK
    varchar paddle_plan_id
    varchar billing_interval
    integer monthly_pageview_limit
    integer site_limit
    integer team_member_limit
    array features
    integer hourly_api_request_limit
    integer user_id
    timestamp inserted_at
    timestamp updated_at
  }
  subscriptions {
    integer id PK
    varchar paddle_subscription_id
    varchar paddle_plan_id
    varchar update_url
    varchar cancel_url
    varchar status
    varchar next_bill_amount
    date next_bill_date
    date last_bill_date
    varchar currency_code
    integer user_id
    timestamp inserted_at
    timestamp updated_at
  }
  events_v2 {
    unknown name
    unknown site_id
    varchar hostname
    varchar pathname
    unknown user_id
    unknown session_id
    timestamp timestamp
    unknown revenue_source_amount
    unknown revenue_source_currency
    unknown revenue_reporting_amount
    unknown revenue_reporting_currency
    varchar referrer
    varchar referrer_source
    varchar utm_medium
    varchar utm_source
    varchar utm_campaign
    varchar utm_content
    varchar utm_term
    unknown country_code
    unknown subdivision1_code
    unknown subdivision2_code
    unknown city_geoname_id
    unknown screen_size
    unknown operating_system
    unknown operating_system_version
    unknown browser
    unknown browser_version
  }
  sessions_v2 {
    varchar hostname
    unknown site_id
    unknown user_id
    unknown session_id
    timestamp start
    unknown duration
    unknown is_bounce
    varchar entry_page
    varchar exit_page
    varchar exit_page_hostname
    unknown pageviews
    unknown events
    unknown sign
    varchar utm_medium
    varchar utm_source
    varchar utm_campaign
    varchar utm_content
    varchar utm_term
    varchar referrer
    varchar referrer_source
    unknown country_code
    unknown subdivision1_code
    unknown subdivision2_code
    unknown city_geoname_id
    unknown screen_size
    unknown operating_system
    unknown operating_system_version
    unknown browser
    unknown browser_version
    timestamp timestamp
    varchar transferred_from
  }
  domains_lookup {
    unknown site_id
    varchar domain
  }
  funnels {
    integer id PK
    varchar name
    integer site_id
    timestamp inserted_at
    timestamp updated_at
  }
  funnel_steps {
    integer id PK
    integer step_order
    integer funnel_id
    integer goal_id
    timestamp inserted_at
    timestamp updated_at
  }
  goals {
    integer id PK
    varchar event_name
    varchar page_path
    varchar currency
    integer site_id
    timestamp inserted_at
    timestamp updated_at
  }
  imported_browsers {
    unknown site_id
    unknown import_id
    date date
    varchar browser
    varchar browser_version
    unknown visitors
    unknown visits
    unknown visit_duration
    unknown pageviews
    unknown bounces
  }
  imported_devices {
    unknown site_id
    unknown import_id
    date date
    varchar device
    unknown visitors
    unknown visits
    unknown visit_duration
    unknown pageviews
    unknown bounces
  }
  imported_entry_pages {
    unknown site_id
    unknown import_id
    date date
    varchar entry_page
    unknown visitors
    unknown entrances
    unknown visit_duration
    unknown pageviews
    unknown bounces
  }
  imported_exit_pages {
    unknown site_id
    unknown import_id
    date date
    varchar exit_page
    unknown exits
    unknown visitors
    unknown visit_duration
    unknown pageviews
    unknown bounces
  }
  imported_locations {
    unknown site_id
    unknown import_id
    date date
    varchar country
    varchar region
    unknown city
    unknown visitors
    unknown visits
    unknown visit_duration
    unknown pageviews
    unknown bounces
  }
  imported_operating_systems {
    unknown site_id
    unknown import_id
    date date
    varchar operating_system
    varchar operating_system_version
    unknown visitors
    unknown visits
    unknown visit_duration
    unknown pageviews
    unknown bounces
  }
  imported_pages {
    unknown site_id
    unknown import_id
    date date
    varchar hostname
    varchar page
    unknown visits
    unknown visitors
    unknown active_visitors
    unknown pageviews
    unknown exits
    unknown time_on_page
  }
  site_imports {
    integer id PK
    date start_date
    date end_date
    varchar label
    varchar source
    varchar status
    boolean legacy
    integer site_id
    integer imported_by_id
    timestamp inserted_at
    timestamp updated_at
  }
  imported_sources {
    unknown site_id
    unknown import_id
    date date
    varchar source
    varchar referrer
    varchar utm_source
    varchar utm_medium
    varchar utm_campaign
    varchar utm_content
    varchar utm_term
    unknown visitors
    unknown visits
    unknown visit_duration
    unknown pageviews
    unknown bounces
  }
  imported_visitors {
    unknown site_id
    unknown import_id
    date date
    unknown visitors
    unknown pageviews
    unknown bounces
    unknown visits
    unknown visit_duration
  }
  ingest_counters {
    timestamp event_timebucket
    unknown site_id
    unknown domain
    unknown metric
    unknown value
  }
  plugins_api_tokens {
    uuid id PK
    timestamp inserted_at
    timestamp updated_at
    bytea token_hash
    varchar description
    varchar hint
    timestamp last_used_at
    integer site_id
  }
  shield_rules_country {
    uuid id PK
    integer site_id
    varchar country_code
    varchar action
    varchar added_by
    timestamp inserted_at
    timestamp updated_at
  }
  shield_rules_hostname {
    uuid id PK
    integer site_id
    varchar hostname
    varchar hostname_pattern
    varchar action
    varchar added_by
    timestamp inserted_at
    timestamp updated_at
  }
  shield_rules_ip {
    uuid id PK
    integer site_id
    inet inet
    varchar action
    varchar description
    varchar added_by
    timestamp inserted_at
    timestamp updated_at
  }
  shield_rules_page {
    uuid id PK
    integer site_id
    varchar page_path
    varchar page_path_pattern
    varchar action
    varchar added_by
    timestamp inserted_at
    timestamp updated_at
  }
  sites {
    integer id PK
    varchar domain
    varchar timezone
    boolean public
    boolean locked
    date stats_start_date
    timestamp native_stats_start_at
    array allowed_event_props
    boolean conversions_enabled
    boolean props_enabled
    boolean funnels_enabled
    integer ingest_rate_limit_scale_seconds
    integer ingest_rate_limit_threshold
    varchar domain_changed_from
    timestamp domain_changed_at
    jsonb imported_data
    timestamp inserted_at
    timestamp updated_at
  }
  google_auth {
    integer id PK
    varchar email
    varchar property
    varchar refresh_token
    varchar access_token
    timestamp expires
    integer user_id
    integer site_id
    timestamp inserted_at
    timestamp updated_at
  }
  site_memberships {
    integer id PK
    varchar role
    integer site_id
    integer user_id
    timestamp inserted_at
    timestamp updated_at
  }
  monthly_reports {
    integer id PK
    array recipients
    integer site_id
    timestamp inserted_at
    timestamp updated_at
  }
  shared_links {
    integer id PK
    integer site_id
    varchar name
    varchar slug
    varchar password_hash
    timestamp inserted_at
    timestamp updated_at
  }
  spike_notifications {
    integer id PK
    array recipients
    integer threshold
    timestamp last_sent
    integer site_id
    timestamp inserted_at
    timestamp updated_at
  }
  site_user_preferences {
    integer id PK
    timestamp pinned_at
    integer user_id
    integer site_id
    timestamp inserted_at
    timestamp updated_at
  }
  weekly_reports {
    integer id PK
    array recipients
    integer site_id
    timestamp inserted_at
    timestamp updated_at
  }
  funnels ||--|{ funnel_steps : ""
  goals ||--|{ funnel_steps : ""
  sites ||--|{ funnels : ""
  sites ||--|{ goals : ""
  sites ||--o| google_auth : ""
  sites ||--|{ invitations : ""
  sites ||--o| monthly_reports : ""
  sites ||--|{ plugins_api_tokens : ""
  sites ||--|{ shared_links : ""
  sites ||--|{ shield_rules_country : ""
  sites ||--|{ shield_rules_hostname : ""
  sites ||--|{ shield_rules_ip : ""
  sites ||--|{ shield_rules_page : ""
  sites ||--|{ site_imports : ""
  sites ||--o| site_memberships : ""
  sites ||--|{ site_user_preferences : ""
  sites ||--o| spike_notifications : ""
  sites ||--o| weekly_reports : ""
  users ||--|{ api_keys : ""
  users ||--|{ email_activation_codes : ""
  users ||--o| enterprise_plans : ""
  users ||--o| google_auth : ""
  users ||--|{ invitations : ""
  users ||--|{ site_imports : ""
  users ||--|{ site_memberships : ""
  users ||--|{ site_user_preferences : ""
  users ||--o| subscriptions : ""
  users ||--|{ totp_recovery_codes : ""
