@startuml

hide circle
hide methods
hide fields
skinparam linetype ortho
skinparam defaultFontName Roboto Mono
skinparam shadowing false

namespace Conduit.Accounts #eee685 {
  entity Conduit.Accounts.Projections.User
  entity Conduit.Accounts.Projectors.User.ProjectionVersion
}
namespace Conduit.Blog #f0ffff {
  entity Conduit.Blog.Projections.Article
  entity Conduit.Blog.Projections.Author
  entity Conduit.Blog.Projections.Comment
  entity Conduit.Blog.Projections.FavoritedArticle
  entity Conduit.Blog.Projections.Feed
  entity Conduit.Blog.Projections.Tag
  entity Conduit.Blog.Projectors.Article.ProjectionVersion
  entity Conduit.Blog.Projectors.Tag.ProjectionVersion
}



@enduml
