TableGroup EPISODE {
  episodes
  episode_guests
  episode_hosts
  episode_requests
  episode_sponsors
  episode_stats
  episode_topics
}
TableGroup NEWS {
  news_ads
  news_issues
  news_issue_ads
  news_issue_items
  news_items
  news_item_comments
  news_item_topics
  news_queue
  news_sources
  news_sponsorships
}
TableGroup PODCAST {
  podcasts
  podcast_hosts
  podcast_topics
}
TableGroup POST {
  posts
  post_topics
}


Table benefits {
  id integer [pk]
  offer varchar
  code varchar
  link_url varchar
  notes varchar
  sponsor_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table metacasts {
  id integer [pk]
  name varchar
  description varchar
  keywords varchar
  slug varchar
  is_official boolean
  cover varchar
  filter_query varchar
  inserted_at timestamp
  updated_at timestamp
}

Table people {
  id integer [pk]
  name varchar
  email varchar
  handle varchar
  github_handle varchar
  linkedin_handle varchar
  twitter_handle varchar
  slack_id varchar
  website varchar
  bio varchar
  location varchar
  auth_token varchar
  auth_token_expires_at timestamp
  joined_at timestamp
  signed_in_at timestamp
  approved boolean
  avatar varchar
  admin boolean
  host boolean
  editor boolean
  public_profile boolean
  settings jsonb
  inserted_at timestamp
  updated_at timestamp
}

Table sponsors {
  id integer [pk]
  name varchar
  description varchar
  website varchar
  github_handle varchar
  twitter_handle varchar
  avatar varchar
  color_logo varchar
  dark_logo varchar
  light_logo varchar
  inserted_at timestamp
  updated_at timestamp
}

Table subscriptions {
  id integer [pk]
  unsubscribed_at timestamp
  context varchar
  person_id integer
  podcast_id integer
  item_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table topics {
  id integer [pk]
  name varchar
  slug varchar
  description varchar
  website varchar
  twitter_handle varchar
  icon varchar
  inserted_at timestamp
  updated_at timestamp
}

Table schema_migrations {
  version integer
  inserted_at timestamp
}

Table oban_jobs {
  id integer [pk]
  state varchar
  queue varchar
  worker varchar
  args jsonb
  meta jsonb
  tags array
  errors array
  attempt integer
  attempted_by array
  max_attempts integer
  priority integer
  attempted_at timestamp
  cancelled_at timestamp
  completed_at timestamp
  discarded_at timestamp
  inserted_at timestamp
  scheduled_at timestamp
}

Table episodes {
  id integer [pk]
  slug varchar
  guid varchar
  title varchar
  subtitle varchar
  type integer
  featured boolean
  highlight varchar
  subhighlight varchar
  summary varchar
  notes varchar
  doc_url varchar
  published boolean
  published_at timestamp
  recorded_at timestamp
  recorded_live boolean
  youtube_id varchar
  audio_file varchar
  audio_bytes integer
  audio_duration integer
  plusplus_file varchar
  plusplus_bytes integer
  plusplus_duration integer
  download_count float
  import_count float
  reach_count integer
  transcript array
  podcast_id integer
  request_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table episode_guests {
  id integer [pk]
  position integer
  thanks boolean
  discount_code varchar
  episode_id integer
  person_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table episode_hosts {
  id integer [pk]
  position integer
  person_id integer
  episode_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table episode_requests {
  id integer [pk]
  status integer
  hosts varchar
  guests varchar
  topics varchar
  pitch varchar
  pronunciation varchar
  decline_message varchar
  podcast_id integer
  submitter_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table episode_sponsors {
  id integer [pk]
  position integer
  title varchar
  link_url varchar
  description varchar
  episode_id integer
  sponsor_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table episode_stats {
  id integer [pk]
  date date
  episode_bytes integer
  total_bytes integer
  downloads float
  uniques integer
  demographics jsonb
  episode_id integer
  podcast_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table episode_topics {
  id integer [pk]
  position integer
  topic_id integer
  episode_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table news_ads {
  id integer [pk]
  url varchar
  headline varchar
  story varchar
  image varchar
  active boolean
  newsletter boolean
  impression_count integer
  click_count integer
  sponsorship_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table news_issues {
  id integer [pk]
  slug varchar
  note varchar
  teaser varchar
  published boolean
  published_at timestamp
  inserted_at timestamp
  updated_at timestamp
}

Table news_issue_ads {
  id integer [pk]
  position integer
  image boolean
  ad_id integer
  issue_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table news_issue_items {
  id integer [pk]
  position integer
  image boolean
  issue_id integer
  item_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table news_items {
  id integer [pk]
  status integer
  type integer
  url varchar
  headline varchar
  story varchar
  image varchar
  object_id varchar
  feed_only boolean
  pinned boolean
  published_at timestamp
  refreshed_at timestamp
  impression_count integer
  click_count integer
  decline_message varchar
  author_id integer
  logger_id integer
  submitter_id integer
  source_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table news_item_comments {
  id integer [pk]
  content varchar
  approved boolean
  edited_at timestamp
  deleted_at timestamp
  item_id integer
  author_id integer
  parent_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table news_item_topics {
  id integer [pk]
  position integer
  item_id integer
  topic_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table news_queue {
  id integer [pk]
  position float
  item_id integer
}

Table news_sources {
  id integer [pk]
  name varchar
  slug varchar
  website varchar
  twitter_handle varchar
  description varchar
  feed varchar
  regex varchar
  icon varchar
  inserted_at timestamp
  updated_at timestamp
}

Table news_sponsorships {
  id integer [pk]
  name varchar
  weeks array
  impression_count integer
  click_count integer
  sponsor_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table podcasts {
  id integer [pk]
  name varchar
  slug varchar
  status integer
  welcome varchar
  description varchar
  extended_description varchar
  vanity_domain varchar
  keywords varchar
  twitter_handle varchar
  apple_url varchar
  spotify_url varchar
  riverside_url varchar
  schedule_note varchar
  download_count float
  reach_count integer
  recorded_live boolean
  partner boolean
  position integer
  subscribers jsonb
  cover varchar
  inserted_at timestamp
  updated_at timestamp
}

Table podcast_hosts {
  id integer [pk]
  position integer
  retired boolean
  person_id integer
  podcast_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table podcast_topics {
  id integer [pk]
  position integer
  podcast_id integer
  topic_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table posts {
  id integer [pk]
  title varchar
  subtitle varchar
  slug varchar
  guid varchar
  canonical_url varchar
  image varchar
  tldr varchar
  body varchar
  published boolean
  published_at timestamp
  author_id integer
  editor_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table post_topics {
  id integer [pk]
  position integer
  topic_id integer
  post_id integer
  inserted_at timestamp
  updated_at timestamp
}

Ref: episode_requests.id - episodes.request_id
Ref: episodes.id < episode_guests.episode_id
Ref: episodes.id < episode_hosts.episode_id
Ref: episodes.id < episode_sponsors.episode_id
Ref: episodes.id < episode_stats.episode_id
Ref: episodes.id < episode_topics.episode_id
Ref: news_ads.id < news_issue_ads.ad_id
Ref: news_issues.id < news_issue_ads.issue_id
Ref: news_issues.id < news_issue_items.issue_id
Ref: news_item_comments.id < news_item_comments.parent_id
Ref: news_items.id < news_issue_items.item_id
Ref: news_items.id < news_item_comments.item_id
Ref: news_items.id < news_item_topics.item_id
Ref: news_items.id - news_queue.item_id
Ref: news_items.id < subscriptions.item_id
Ref: news_sources.id < news_items.source_id
Ref: news_sponsorships.id < news_ads.sponsorship_id
Ref: people.id < episode_guests.person_id
Ref: people.id < episode_hosts.person_id
Ref: people.id < episode_requests.submitter_id
Ref: people.id < news_item_comments.author_id
Ref: people.id < news_items.author_id
Ref: people.id < news_items.logger_id
Ref: people.id < news_items.submitter_id
Ref: people.id < podcast_hosts.person_id
Ref: people.id < posts.author_id
Ref: people.id < posts.editor_id
Ref: people.id < subscriptions.person_id
Ref: podcasts.id < episode_requests.podcast_id
Ref: podcasts.id < episode_stats.podcast_id
Ref: podcasts.id < episodes.podcast_id
Ref: podcasts.id < podcast_hosts.podcast_id
Ref: podcasts.id < podcast_topics.podcast_id
Ref: podcasts.id < subscriptions.podcast_id
Ref: posts.id < post_topics.post_id
Ref: sponsors.id < benefits.sponsor_id
Ref: sponsors.id < episode_sponsors.sponsor_id
Ref: sponsors.id < news_sponsorships.sponsor_id
Ref: topics.id < episode_topics.topic_id
Ref: topics.id < news_item_topics.topic_id
Ref: topics.id < podcast_topics.topic_id
Ref: topics.id < post_topics.topic_id