@startuml

hide circle
hide methods
hide fields
skinparam linetype ortho
skinparam defaultFontName Roboto Mono
skinparam shadowing false

namespace ChatApi.Accounts #eee685 {
  entity ChatApi.Accounts.Account
  entity ChatApi.Accounts.Settings
  entity ChatApi.Accounts.WorkingHours
}
namespace ChatApi.ApiKeys #8deeee {
  entity ChatApi.ApiKeys.PersonalApiKey
}
namespace ChatApi.Auth #eee5de {
  entity ChatApi.Auth.PowSession
}
namespace ChatApi.BrowserReplayEvents #b4eeb4 {
  entity ChatApi.BrowserReplayEvents.BrowserReplayEvent
}
namespace ChatApi.BrowserSessions #f0f8ff {
  entity ChatApi.BrowserSessions.BrowserSession
}
namespace ChatApi.CannedResponses #eee685 {
  entity ChatApi.CannedResponses.CannedResponse
}
namespace ChatApi.Companies #b4eeb4 {
  entity ChatApi.Companies.Company
}
namespace ChatApi.Conversations #f0f8ff {
  entity ChatApi.Conversations.Conversation
}
namespace ChatApi.Customers #f0f8ff {
  entity ChatApi.Customers.Customer
}
namespace ChatApi.EventSubscriptions #b4eeb4 {
  entity ChatApi.EventSubscriptions.EventSubscription
}
namespace ChatApi.Files #eee5de {
  entity ChatApi.Files.FileUpload
}
namespace ChatApi.Github #eee5de {
  entity ChatApi.Github.GithubAuthorization
}
namespace ChatApi.Google #eee5de {
  entity ChatApi.Google.GmailConversationThread
  entity ChatApi.Google.GoogleAuthorization
}
namespace ChatApi.Issues #eee5de {
  entity ChatApi.Issues.ConversationIssue
  entity ChatApi.Issues.CustomerIssue
  entity ChatApi.Issues.Issue
}
namespace ChatApi.Lambdas #b4eeb4 {
  entity ChatApi.Lambdas.Lambda
}
namespace ChatApi.Mattermost #eee685 {
  entity ChatApi.Mattermost.MattermostAuthorization
  entity ChatApi.Mattermost.MattermostConversationThread
}
namespace ChatApi.Mentions #eee5de {
  entity ChatApi.Mentions.Mention
}
namespace ChatApi.Messages #f0f8ff {
  entity ChatApi.Messages.Message
  entity ChatApi.Messages.MessageFile
}
namespace ChatApi.Notes #eee5de {
  entity ChatApi.Notes.Note
}
namespace ChatApi.SlackAuthorizations #f0ffff {
  entity ChatApi.SlackAuthorizations.Settings
  entity ChatApi.SlackAuthorizations.SlackAuthorization
}
namespace ChatApi.SlackConversationThreads #eee685 {
  entity ChatApi.SlackConversationThreads.SlackConversationThread
}
namespace ChatApi.Tags #8deeee {
  entity ChatApi.Tags.ConversationTag
  entity ChatApi.Tags.CustomerTag
  entity ChatApi.Tags.Tag
}
namespace ChatApi.Twilio #b4eeb4 {
  entity ChatApi.Twilio.TwilioAuthorization
}
namespace ChatApi.UserInvitations #b4eeb4 {
  entity ChatApi.UserInvitations.UserInvitation
}
namespace ChatApi.Users #f0f8ff {
  entity ChatApi.Users.User
  entity ChatApi.Users.UserProfile
  entity ChatApi.Users.UserSettings
}
namespace ChatApi.WidgetSettings #ffefd5 {
  entity ChatApi.WidgetSettings.WidgetSetting
}
namespace Ecto.Migration #f0f8ff {
  entity Ecto.Migration.SchemaMigration
}
namespace Oban.Job #b4eeb4 {
  entity Oban.Job
}


ChatApi.Accounts.Account ||--|{ ChatApi.BrowserReplayEvents.BrowserReplayEvent
ChatApi.Accounts.Account ||--|{ ChatApi.BrowserSessions.BrowserSession
ChatApi.Accounts.Account ||--|{ ChatApi.CannedResponses.CannedResponse
ChatApi.Accounts.Account ||--|{ ChatApi.Companies.Company
ChatApi.Accounts.Account ||--|{ ChatApi.Issues.ConversationIssue
ChatApi.Accounts.Account ||--|{ ChatApi.Tags.ConversationTag
ChatApi.Accounts.Account ||--|{ ChatApi.Conversations.Conversation
ChatApi.Accounts.Account ||--|{ ChatApi.Issues.CustomerIssue
ChatApi.Accounts.Account ||--|{ ChatApi.Tags.CustomerTag
ChatApi.Accounts.Account ||--|{ ChatApi.Customers.Customer
ChatApi.Accounts.Account ||--|{ ChatApi.EventSubscriptions.EventSubscription
ChatApi.Accounts.Account ||--|{ ChatApi.Files.FileUpload
ChatApi.Accounts.Account ||--|{ ChatApi.Github.GithubAuthorization
ChatApi.Accounts.Account ||--|{ ChatApi.Google.GmailConversationThread
ChatApi.Accounts.Account ||--|{ ChatApi.Google.GoogleAuthorization
ChatApi.Accounts.Account ||--|{ ChatApi.Issues.Issue
ChatApi.Accounts.Account ||--|{ ChatApi.Lambdas.Lambda
ChatApi.Accounts.Account ||--|{ ChatApi.Mattermost.MattermostAuthorization
ChatApi.Accounts.Account ||--|{ ChatApi.Mattermost.MattermostConversationThread
ChatApi.Accounts.Account ||--|{ ChatApi.Mentions.Mention
ChatApi.Accounts.Account ||--|{ ChatApi.Messages.MessageFile
ChatApi.Accounts.Account ||--|{ ChatApi.Messages.Message
ChatApi.Accounts.Account ||--|{ ChatApi.Notes.Note
ChatApi.Accounts.Account ||--|{ ChatApi.ApiKeys.PersonalApiKey
ChatApi.Accounts.Account ||--|{ ChatApi.SlackAuthorizations.SlackAuthorization
ChatApi.Accounts.Account ||--|{ ChatApi.SlackConversationThreads.SlackConversationThread
ChatApi.Accounts.Account ||--|{ ChatApi.Tags.Tag
ChatApi.Accounts.Account ||--|{ ChatApi.Twilio.TwilioAuthorization
ChatApi.Accounts.Account ||--|{ ChatApi.UserInvitations.UserInvitation
ChatApi.Accounts.Account ||--|{ ChatApi.Users.User
ChatApi.Accounts.Account ||--o| ChatApi.WidgetSettings.WidgetSetting
ChatApi.Accounts.Account ||--o| ChatApi.Accounts.Settings
ChatApi.Accounts.Account ||--|{ ChatApi.Accounts.WorkingHours
ChatApi.BrowserSessions.BrowserSession ||--|{ ChatApi.BrowserReplayEvents.BrowserReplayEvent
ChatApi.Companies.Company ||--|{ ChatApi.Customers.Customer
ChatApi.Conversations.Conversation ||--|{ ChatApi.Issues.ConversationIssue
ChatApi.Conversations.Conversation ||--|{ ChatApi.Tags.ConversationTag
ChatApi.Conversations.Conversation ||--|{ ChatApi.Google.GmailConversationThread
ChatApi.Conversations.Conversation ||--|{ ChatApi.Mattermost.MattermostConversationThread
ChatApi.Conversations.Conversation ||--|{ ChatApi.Mentions.Mention
ChatApi.Conversations.Conversation ||--|{ ChatApi.Messages.Message
ChatApi.Conversations.Conversation ||--|{ ChatApi.SlackConversationThreads.SlackConversationThread
ChatApi.Customers.Customer ||--|{ ChatApi.BrowserSessions.BrowserSession
ChatApi.Customers.Customer ||--|{ ChatApi.Conversations.Conversation
ChatApi.Customers.Customer ||--|{ ChatApi.Issues.CustomerIssue
ChatApi.Customers.Customer ||--|{ ChatApi.Tags.CustomerTag
ChatApi.Customers.Customer ||--|{ ChatApi.Files.FileUpload
ChatApi.Customers.Customer ||--|{ ChatApi.Messages.Message
ChatApi.Customers.Customer ||--|{ ChatApi.Notes.Note
ChatApi.Files.FileUpload ||--|{ ChatApi.Messages.MessageFile
ChatApi.Issues.Issue ||--|{ ChatApi.Issues.ConversationIssue
ChatApi.Issues.Issue ||--|{ ChatApi.Issues.CustomerIssue
ChatApi.Messages.Message ||--|{ ChatApi.Mentions.Mention
ChatApi.Messages.Message ||--|{ ChatApi.Messages.MessageFile
ChatApi.SlackAuthorizations.SlackAuthorization ||--o| ChatApi.SlackAuthorizations.Settings
ChatApi.Tags.Tag ||--|{ ChatApi.Tags.ConversationTag
ChatApi.Tags.Tag ||--|{ ChatApi.Tags.CustomerTag
ChatApi.Users.User ||--|{ ChatApi.Issues.ConversationIssue
ChatApi.Users.User ||--|{ ChatApi.Tags.ConversationTag
ChatApi.Users.User ||--|{ ChatApi.Conversations.Conversation
ChatApi.Users.User ||--|{ ChatApi.Issues.CustomerIssue
ChatApi.Users.User ||--|{ ChatApi.Tags.CustomerTag
ChatApi.Users.User ||--|{ ChatApi.Files.FileUpload
ChatApi.Users.User ||--|{ ChatApi.Github.GithubAuthorization
ChatApi.Users.User ||--|{ ChatApi.Google.GoogleAuthorization
ChatApi.Users.User ||--|{ ChatApi.Issues.Issue
ChatApi.Users.User ||--|{ ChatApi.Lambdas.Lambda
ChatApi.Users.User ||--|{ ChatApi.Mattermost.MattermostAuthorization
ChatApi.Users.User ||--|{ ChatApi.Mentions.Mention
ChatApi.Users.User ||--|{ ChatApi.Messages.Message
ChatApi.Users.User ||--|{ ChatApi.Notes.Note
ChatApi.Users.User ||--|{ ChatApi.ApiKeys.PersonalApiKey
ChatApi.Users.User ||--|{ ChatApi.Tags.Tag
ChatApi.Users.User ||--|{ ChatApi.Twilio.TwilioAuthorization
ChatApi.Users.User ||--o| ChatApi.Users.UserProfile
ChatApi.Users.User ||--o| ChatApi.Users.UserSettings
@enduml
