TableGroup "ChatApi.Accounts" {
  accounts
}
TableGroup "ChatApi.ApiKeys" {
  personal_api_keys
}
TableGroup "ChatApi.Auth" {
  pow_sessions
}
TableGroup "ChatApi.BrowserReplayEvents" {
  browser_replay_events
}
TableGroup "ChatApi.BrowserSessions" {
  browser_sessions
}
TableGroup "ChatApi.CannedResponses" {
  canned_responses
}
TableGroup "ChatApi.Companies" {
  companies
}
TableGroup "ChatApi.Conversations" {
  conversations
}
TableGroup "ChatApi.Customers" {
  customers
}
TableGroup "ChatApi.EventSubscriptions" {
  event_subscriptions
}
TableGroup "ChatApi.Files" {
  files
}
TableGroup "ChatApi.Github" {
  github_authorizations
}
TableGroup "ChatApi.Google" {
  gmail_conversation_threads
  google_authorizations
}
TableGroup "ChatApi.Issues" {
  conversation_issues
  customer_issues
  issues
}
TableGroup "ChatApi.Lambdas" {
  lambdas
}
TableGroup "ChatApi.Mattermost" {
  mattermost_authorizations
  mattermost_conversation_threads
}
TableGroup "ChatApi.Mentions" {
  mentions
}
TableGroup "ChatApi.Messages" {
  messages
  message_files
}
TableGroup "ChatApi.Notes" {
  notes
}
TableGroup "ChatApi.SlackAuthorizations" {
  slack_authorizations
}
TableGroup "ChatApi.SlackConversationThreads" {
  slack_conversation_threads
}
TableGroup "ChatApi.Tags" {
  conversation_tags
  customer_tags
  tags
}
TableGroup "ChatApi.Twilio" {
  twilio_authorizations
}
TableGroup "ChatApi.UserInvitations" {
  user_invitations
}
TableGroup "ChatApi.Users" {
  users
  user_profiles
  user_settings
}
TableGroup "ChatApi.WidgetSettings" {
  widget_settings
}
TableGroup "Ecto.Migration" {
  schema_migrations
}
TableGroup "Oban.Job" {
  oban_jobs
}


Table accounts {
  id uuid [pk]
  company_name varchar
  company_logo_url varchar
  time_zone varchar
  subscription_plan varchar
  stripe_customer_id varchar
  stripe_subscription_id varchar
  stripe_product_id varchar
  stripe_default_payment_method_id varchar
  settings jsonb
  working_hours jsonb
  inserted_at timestamp
  updated_at timestamp
}

Table personal_api_keys {
  id uuid [pk]
  label varchar
  value varchar
  last_used_at timestamp
  account_id uuid
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table pow_sessions {
  namespace varchar
  key array
  original_key bytea
  value bytea
  expires_at timestamp
  inserted_at timestamp
  updated_at timestamp
}

Table browser_replay_events {
  id uuid [pk]
  event jsonb
  timestamp timestamp
  account_id uuid
  browser_session_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table browser_sessions {
  id uuid [pk]
  finished_at timestamp
  started_at timestamp
  metadata jsonb
  account_id uuid
  customer_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table canned_responses {
  id uuid [pk]
  content varchar
  name varchar
  account_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table companies {
  id uuid [pk]
  name varchar
  description varchar
  external_id varchar
  website_url varchar
  industry varchar
  logo_image_url varchar
  slack_channel_id varchar
  slack_channel_name varchar
  slack_team_id varchar
  slack_team_name varchar
  metadata jsonb
  account_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table conversations {
  id uuid [pk]
  status varchar
  priority varchar
  source varchar
  subject varchar
  read boolean
  archived_at timestamp
  first_replied_at timestamp
  closed_at timestamp
  last_activity_at timestamp
  metadata jsonb
  assignee_id integer
  account_id uuid
  customer_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table customers {
  id uuid [pk]
  first_seen date
  email varchar
  name varchar
  phone varchar
  external_id varchar
  profile_photo_url varchar
  browser varchar
  browser_version varchar
  browser_language varchar
  os varchar
  ip varchar
  last_seen_at timestamp
  current_url varchar
  host varchar
  pathname varchar
  screen_height integer
  screen_width integer
  lib varchar
  time_zone varchar
  metadata jsonb
  account_id uuid
  company_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table event_subscriptions {
  id uuid [pk]
  scope varchar
  webhook_url varchar
  verified boolean
  account_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table files {
  id uuid [pk]
  filename varchar
  file_url varchar
  unique_filename varchar
  content_type varchar
  account_id uuid
  customer_id uuid
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table github_authorizations {
  id uuid [pk]
  access_token varchar
  access_token_expires_at timestamp
  refresh_token varchar
  refresh_token_expires_at timestamp
  token_type varchar
  scope varchar
  github_installation_id varchar
  metadata jsonb
  settings jsonb
  account_id uuid
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table gmail_conversation_threads {
  id uuid [pk]
  gmail_thread_id varchar
  gmail_initial_subject varchar
  last_gmail_message_id varchar
  last_gmail_history_id varchar
  last_synced_at timestamp
  metadata jsonb
  account_id uuid
  conversation_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table google_authorizations {
  id uuid [pk]
  client varchar
  access_token varchar
  refresh_token varchar
  token_type varchar
  expires_at integer
  scope varchar
  type varchar
  metadata jsonb
  settings jsonb
  account_id uuid
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table conversation_issues {
  id uuid [pk]
  account_id uuid
  conversation_id uuid
  issue_id uuid
  creator_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table customer_issues {
  id uuid [pk]
  account_id uuid
  customer_id uuid
  issue_id uuid
  creator_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table issues {
  id uuid [pk]
  title varchar
  body varchar
  state varchar
  finished_at timestamp
  closed_at timestamp
  github_issue_url varchar
  metadata jsonb
  account_id uuid
  creator_id integer
  assignee_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table lambdas {
  id uuid [pk]
  code varchar
  description varchar
  language varchar
  last_deployed_at timestamp
  last_executed_at timestamp
  metadata jsonb
  name varchar
  runtime varchar
  status varchar
  lambda_function_name varchar
  lambda_function_handler varchar
  lambda_revision_id varchar
  lambda_last_update_status varchar
  account_id uuid
  creator_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table mattermost_authorizations {
  id uuid [pk]
  access_token varchar
  refresh_token varchar
  bot_token varchar
  verification_token varchar
  mattermost_url varchar
  channel_id varchar
  channel_name varchar
  team_id varchar
  team_domain varchar
  webhook_url varchar
  scope varchar
  metadata jsonb
  settings jsonb
  account_id uuid
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table mattermost_conversation_threads {
  id uuid [pk]
  mattermost_channel_id varchar
  mattermost_post_root_id varchar
  account_id uuid
  conversation_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table mentions {
  id uuid [pk]
  seen_at timestamp
  account_id uuid
  conversation_id uuid
  message_id uuid
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table messages {
  id uuid [pk]
  body varchar
  sent_at timestamp
  seen_at timestamp
  source varchar
  type varchar
  subject varchar
  private boolean
  metadata jsonb
  conversation_id uuid
  account_id uuid
  customer_id uuid
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table message_files {
  id uuid [pk]
  message_id uuid
  file_id uuid
  account_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table notes {
  id uuid [pk]
  body varchar
  account_id uuid
  customer_id uuid
  author_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table slack_authorizations {
  id uuid [pk]
  access_token varchar
  type varchar
  app_id varchar
  authed_user_id varchar
  bot_user_id varchar
  channel varchar
  channel_id varchar
  configuration_url varchar
  scope varchar
  team_id varchar
  team_name varchar
  token_type varchar
  webhook_url varchar
  metadata jsonb
  settings jsonb
  account_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table slack_conversation_threads {
  id uuid [pk]
  slack_channel varchar
  slack_team varchar
  slack_thread_ts varchar
  account_id uuid
  conversation_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table conversation_tags {
  id uuid [pk]
  account_id uuid
  conversation_id uuid
  tag_id uuid
  creator_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table customer_tags {
  id uuid [pk]
  account_id uuid
  customer_id uuid
  tag_id uuid
  creator_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table tags {
  id uuid [pk]
  name varchar
  description varchar
  color varchar
  account_id uuid
  creator_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table twilio_authorizations {
  id uuid [pk]
  twilio_auth_token varchar
  twilio_account_sid varchar
  from_phone_number varchar
  metadata jsonb
  settings jsonb
  account_id uuid
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table user_invitations {
  id uuid [pk]
  expires_at timestamp
  account_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table users {
  id integer [pk]
  email_confirmation_token varchar
  password_reset_token varchar
  email_confirmed_at timestamp
  disabled_at timestamp
  archived_at timestamp
  role varchar
  has_valid_email boolean
  account_id uuid
  password_hash varchar
  email varchar
  inserted_at timestamp
  updated_at timestamp
}

Table user_profiles {
  id uuid [pk]
  display_name varchar
  full_name varchar
  profile_photo_url varchar
  slack_user_id varchar
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table user_settings {
  id uuid [pk]
  email_alert_on_new_message boolean
  expo_push_token varchar
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table widget_settings {
  id uuid [pk]
  title varchar
  subtitle varchar
  color varchar
  greeting varchar
  new_message_placeholder varchar
  show_agent_availability boolean
  agent_available_text varchar
  agent_unavailable_text varchar
  require_email_upfront boolean
  is_open_by_default boolean
  is_branding_hidden boolean
  custom_icon_url varchar
  iframe_url_override varchar
  icon_variant varchar
  email_input_placeholder varchar
  new_messages_notification_text varchar
  base_url varchar
  away_message varchar
  host varchar
  pathname varchar
  last_seen_at timestamp
  account_id uuid
  inserted_at timestamp
  updated_at timestamp
}

Table schema_migrations {
  version integer
  inserted_at timestamp
}

Table oban_jobs {
  id integer [pk]
  state varchar
  queue varchar
  worker varchar
  args jsonb
  errors array
  tags array
  attempt integer
  attempted_by array
  max_attempts integer
  priority integer
  attempted_at timestamp
  completed_at timestamp
  discarded_at timestamp
  inserted_at timestamp
  scheduled_at timestamp
}

Ref: accounts.id < browser_replay_events.account_id
Ref: accounts.id < browser_sessions.account_id
Ref: accounts.id < canned_responses.account_id
Ref: accounts.id < companies.account_id
Ref: accounts.id < conversation_issues.account_id
Ref: accounts.id < conversation_tags.account_id
Ref: accounts.id < conversations.account_id
Ref: accounts.id < customer_issues.account_id
Ref: accounts.id < customer_tags.account_id
Ref: accounts.id < customers.account_id
Ref: accounts.id < event_subscriptions.account_id
Ref: accounts.id < files.account_id
Ref: accounts.id < github_authorizations.account_id
Ref: accounts.id < gmail_conversation_threads.account_id
Ref: accounts.id < google_authorizations.account_id
Ref: accounts.id < issues.account_id
Ref: accounts.id < lambdas.account_id
Ref: accounts.id < mattermost_authorizations.account_id
Ref: accounts.id < mattermost_conversation_threads.account_id
Ref: accounts.id < mentions.account_id
Ref: accounts.id < message_files.account_id
Ref: accounts.id < messages.account_id
Ref: accounts.id < notes.account_id
Ref: accounts.id < personal_api_keys.account_id
Ref: accounts.id < slack_authorizations.account_id
Ref: accounts.id < slack_conversation_threads.account_id
Ref: accounts.id < tags.account_id
Ref: accounts.id < twilio_authorizations.account_id
Ref: accounts.id < user_invitations.account_id
Ref: accounts.id < users.account_id
Ref: accounts.id - widget_settings.account_id
Ref: browser_sessions.id < browser_replay_events.browser_session_id
Ref: companies.id < customers.company_id
Ref: conversations.id < conversation_issues.conversation_id
Ref: conversations.id < conversation_tags.conversation_id
Ref: conversations.id < gmail_conversation_threads.conversation_id
Ref: conversations.id < mattermost_conversation_threads.conversation_id
Ref: conversations.id < mentions.conversation_id
Ref: conversations.id < messages.conversation_id
Ref: conversations.id < slack_conversation_threads.conversation_id
Ref: customers.id < browser_sessions.customer_id
Ref: customers.id < conversations.customer_id
Ref: customers.id < customer_issues.customer_id
Ref: customers.id < customer_tags.customer_id
Ref: customers.id < files.customer_id
Ref: customers.id < messages.customer_id
Ref: customers.id < notes.customer_id
Ref: files.id < message_files.file_id
Ref: issues.id < conversation_issues.issue_id
Ref: issues.id < customer_issues.issue_id
Ref: messages.id < mentions.message_id
Ref: messages.id < message_files.message_id
Ref: tags.id < conversation_tags.tag_id
Ref: tags.id < customer_tags.tag_id
Ref: users.id < conversation_issues.creator_id
Ref: users.id < conversation_tags.creator_id
Ref: users.id < conversations.assignee_id
Ref: users.id < customer_issues.creator_id
Ref: users.id < customer_tags.creator_id
Ref: users.id < files.user_id
Ref: users.id < github_authorizations.user_id
Ref: users.id < google_authorizations.user_id
Ref: users.id < issues.assignee_id
Ref: users.id < issues.creator_id
Ref: users.id < lambdas.creator_id
Ref: users.id < mattermost_authorizations.user_id
Ref: users.id < mentions.user_id
Ref: users.id < messages.user_id
Ref: users.id < notes.author_id
Ref: users.id < personal_api_keys.user_id
Ref: users.id < tags.creator_id
Ref: users.id < twilio_authorizations.user_id
Ref: users.id - user_profiles.user_id
Ref: users.id - user_settings.user_id