
Enum billing_interval {
  yearly
  monthly
}

Enum currency {
  KMF
  AUD
  SAR
  BWP
  BBD
  EGP
  YER
  CDF
  IQD
  MRU
  JOD
  XPT
  XBB
  NGN
  BDT
  CNY
  ANG
  GTQ
  HTG
  TWD
  OMR
  STN
  AOA
  MUR
  XCD
  TND
  THB
  KES
  GIP
  MZN
  ERN
  MAD
  FKP
  MVR
  BND
  KZT
  EUR
  SYP
  MYR
  RSD
  KRW
  COU
  GMD
  ILS
  BAM
  XAG
  AZN
  AFN
  AWG
  SOS
  PAB
  AED
  UYI
  BTN
  USN
  KPW
  IDR
  XPD
  MOP
  GEL
  MXV
  CHW
  XAF
  UGX
  DJF
  SGD
  PGK
  IRR
  VES
  PHP
  SSP
  BOB
  XDR
  JPY
  BHD
  UAH
  ZAR
  BSD
  TMT
  XOF
  XTS
  MNT
  XSU
  XPF
  TTD
  PLN
  AMD
  SBD
  LSL
  GBP
  DOP
  SEK
  MDL
  CUP
  CZK
  SZL
  COP
  XAU
  NOK
  CLF
  RWF
  NAD
  KHR
  TRY
  LAK
  SDG
  XXX
  PEN
  LBP
  BZD
  CLP
  KGS
  TZS
  GNF
  KWD
  NZD
  SVC
  LRD
  CHF
  PKR
  SHP
  XUA
  XBD
  LYD
  BIF
  JMD
  ALL
  BYN
  CUC
  UZS
  MKD
  ZWL
  RON
  NIO
  MMK
  SRD
  ETB
  ARS
  GHS
  XBA
  XBC
  UYW
  HKD
  ISK
  DZD
  MWK
  RUB
  SLL
  SCR
  CHE
  CVE
  VND
  ZMW
  HNL
  HUF
  INR
  DKK
  FJD
  HRK
  UYU
  PYG
  BMD
  KYD
  VUV
  BGN
  TOP
  MXN
  CAD
  MGA
  BOV
  BRL
  WST
  NPR
  CRC
  GYD
  TJS
  LKR
  QAR
  USD
}

Enum role {
  owner
  admin
  viewer
}

Enum action {
  allow
  deny
}

Enum source {
  noop
  csv
  universal_analytics
  google_analytics_4
}

Enum site_imports_status {
  pending
  failed
  completed
  importing
}

Enum subscriptions_status {
  active
  deleted
  past_due
  paused
}

Enum theme {
  system
  light
  dark
}

Table schema_migrations {
  version integer [pk]
  inserted_at timestamp
}

Table fun_with_flags_toggles {
  id integer [pk]
  flag_name varchar
  gate_type varchar
  target varchar
  enabled boolean
}

Table oban_jobs {
  id integer [pk]
  state varchar
  queue varchar
  worker varchar
  args jsonb
  meta jsonb
  tags array
  errors array
  attempt integer
  attempted_by array
  max_attempts integer
  priority integer
  attempted_at timestamp
  cancelled_at timestamp
  completed_at timestamp
  discarded_at timestamp
  inserted_at timestamp
  scheduled_at timestamp
}

Table api_keys {
  id integer [pk]
  name varchar
  scopes array
  hourly_request_limit integer
  key_hash varchar
  key_prefix varchar
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table email_activation_codes {
  id integer [pk]
  code varchar
  issued_at timestamp
  user_id integer
}

Table invitations {
  id integer [pk]
  invitation_id varchar
  email varchar
  role role
  inviter_id integer
  site_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table totp_recovery_codes {
  id integer [pk]
  code_digest varchar
  user_id integer
  inserted_at timestamp
}

Table users {
  id integer [pk]
  email varchar
  password_hash varchar
  name varchar
  last_seen timestamp
  trial_expiry_date date
  theme theme
  email_verified boolean
  previous_email varchar
  accept_traffic_until date
  allow_next_upgrade_override boolean
  totp_enabled boolean
  totp_secret bytea
  totp_token varchar
  totp_last_used_at timestamp
  grace_period jsonb
  inserted_at timestamp
  updated_at timestamp
}

Table enterprise_plans {
  id integer [pk]
  paddle_plan_id varchar
  billing_interval billing_interval
  monthly_pageview_limit integer
  site_limit integer
  team_member_limit integer
  features array
  hourly_api_request_limit integer
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table subscriptions {
  id integer [pk]
  paddle_subscription_id varchar
  paddle_plan_id varchar
  update_url varchar
  cancel_url varchar
  status subscriptions_status
  next_bill_amount varchar
  next_bill_date date
  last_bill_date date
  currency_code varchar
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table events_v2 {
  name unknown
  site_id unknown
  hostname varchar
  pathname varchar
  user_id unknown
  session_id unknown
  timestamp timestamp
  "meta.key" array
  "meta.value" array
  revenue_source_amount unknown
  revenue_source_currency unknown
  revenue_reporting_amount unknown
  revenue_reporting_currency unknown
  referrer varchar
  referrer_source varchar
  utm_medium varchar
  utm_source varchar
  utm_campaign varchar
  utm_content varchar
  utm_term varchar
  country_code unknown
  subdivision1_code unknown
  subdivision2_code unknown
  city_geoname_id unknown
  screen_size unknown
  operating_system unknown
  operating_system_version unknown
  browser unknown
  browser_version unknown
}

Table sessions_v2 {
  hostname varchar
  site_id unknown
  user_id unknown
  session_id unknown
  start timestamp
  duration unknown
  is_bounce unknown
  entry_page varchar
  exit_page varchar
  exit_page_hostname varchar
  pageviews unknown
  events unknown
  sign unknown
  "entry_meta.key" array
  "entry_meta.value" array
  utm_medium varchar
  utm_source varchar
  utm_campaign varchar
  utm_content varchar
  utm_term varchar
  referrer varchar
  referrer_source varchar
  country_code unknown
  subdivision1_code unknown
  subdivision2_code unknown
  city_geoname_id unknown
  screen_size unknown
  operating_system unknown
  operating_system_version unknown
  browser unknown
  browser_version unknown
  timestamp timestamp
  transferred_from varchar
}

Table domains_lookup {
  site_id unknown
  domain varchar
}

Table funnels {
  id integer [pk]
  name varchar
  site_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table funnel_steps {
  id integer [pk]
  step_order integer
  funnel_id integer
  goal_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table goals {
  id integer [pk]
  event_name varchar
  page_path varchar
  currency currency
  site_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table imported_browsers {
  site_id unknown
  import_id unknown
  date date
  browser varchar
  browser_version varchar
  visitors unknown
  visits unknown
  visit_duration unknown
  pageviews unknown
  bounces unknown
}

Table imported_devices {
  site_id unknown
  import_id unknown
  date date
  device varchar
  visitors unknown
  visits unknown
  visit_duration unknown
  pageviews unknown
  bounces unknown
}

Table imported_entry_pages {
  site_id unknown
  import_id unknown
  date date
  entry_page varchar
  visitors unknown
  entrances unknown
  visit_duration unknown
  pageviews unknown
  bounces unknown
}

Table imported_exit_pages {
  site_id unknown
  import_id unknown
  date date
  exit_page varchar
  exits unknown
  visitors unknown
  visit_duration unknown
  pageviews unknown
  bounces unknown
}

Table imported_locations {
  site_id unknown
  import_id unknown
  date date
  country varchar
  region varchar
  city unknown
  visitors unknown
  visits unknown
  visit_duration unknown
  pageviews unknown
  bounces unknown
}

Table imported_operating_systems {
  site_id unknown
  import_id unknown
  date date
  operating_system varchar
  operating_system_version varchar
  visitors unknown
  visits unknown
  visit_duration unknown
  pageviews unknown
  bounces unknown
}

Table imported_pages {
  site_id unknown
  import_id unknown
  date date
  hostname varchar
  page varchar
  visits unknown
  visitors unknown
  active_visitors unknown
  pageviews unknown
  exits unknown
  time_on_page unknown
}

Table site_imports {
  id integer [pk]
  start_date date
  end_date date
  label varchar
  source source
  status site_imports_status
  legacy boolean
  site_id integer
  imported_by_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table imported_sources {
  site_id unknown
  import_id unknown
  date date
  source varchar
  referrer varchar
  utm_source varchar
  utm_medium varchar
  utm_campaign varchar
  utm_content varchar
  utm_term varchar
  visitors unknown
  visits unknown
  visit_duration unknown
  pageviews unknown
  bounces unknown
}

Table imported_visitors {
  site_id unknown
  import_id unknown
  date date
  visitors unknown
  pageviews unknown
  bounces unknown
  visits unknown
  visit_duration unknown
}

Table ingest_counters {
  event_timebucket timestamp
  site_id unknown
  domain unknown
  metric unknown
  value unknown
}

Table plugins_api_tokens {
  id uuid [pk]
  inserted_at timestamp
  updated_at timestamp
  token_hash bytea
  description varchar
  hint varchar
  last_used_at timestamp
  site_id integer
}

Table shield_rules_country {
  id uuid [pk]
  site_id integer
  country_code varchar
  action action
  added_by varchar
  inserted_at timestamp
  updated_at timestamp
}

Table shield_rules_hostname {
  id uuid [pk]
  site_id integer
  hostname varchar
  hostname_pattern varchar
  action action
  added_by varchar
  inserted_at timestamp
  updated_at timestamp
}

Table shield_rules_ip {
  id uuid [pk]
  site_id integer
  inet inet
  action action
  description varchar
  added_by varchar
  inserted_at timestamp
  updated_at timestamp
}

Table shield_rules_page {
  id uuid [pk]
  site_id integer
  page_path varchar
  page_path_pattern varchar
  action action
  added_by varchar
  inserted_at timestamp
  updated_at timestamp
}

Table sites {
  id integer [pk]
  domain varchar
  timezone varchar
  public boolean
  locked boolean
  stats_start_date date
  native_stats_start_at timestamp
  allowed_event_props array
  conversions_enabled boolean
  props_enabled boolean
  funnels_enabled boolean
  ingest_rate_limit_scale_seconds integer
  ingest_rate_limit_threshold integer
  domain_changed_from varchar
  domain_changed_at timestamp
  imported_data jsonb
  inserted_at timestamp
  updated_at timestamp
}

Table google_auth {
  id integer [pk]
  email varchar
  property varchar
  refresh_token varchar
  access_token varchar
  expires timestamp
  user_id integer
  site_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table site_memberships {
  id integer [pk]
  role role
  site_id integer
  user_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table monthly_reports {
  id integer [pk]
  recipients array
  site_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table shared_links {
  id integer [pk]
  site_id integer
  name varchar
  slug varchar
  password_hash varchar
  inserted_at timestamp
  updated_at timestamp
}

Table spike_notifications {
  id integer [pk]
  recipients array
  threshold integer
  last_sent timestamp
  site_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table site_user_preferences {
  id integer [pk]
  pinned_at timestamp
  user_id integer
  site_id integer
  inserted_at timestamp
  updated_at timestamp
}

Table weekly_reports {
  id integer [pk]
  recipients array
  site_id integer
  inserted_at timestamp
  updated_at timestamp
}

Ref: funnels.id < funnel_steps.funnel_id
Ref: goals.id < funnel_steps.goal_id
Ref: sites.id < funnels.site_id
Ref: sites.id < goals.site_id
Ref: sites.id - google_auth.site_id
Ref: sites.id < invitations.site_id
Ref: sites.id - monthly_reports.site_id
Ref: sites.id < plugins_api_tokens.site_id
Ref: sites.id < shared_links.site_id
Ref: sites.id < shield_rules_country.site_id
Ref: sites.id < shield_rules_hostname.site_id
Ref: sites.id < shield_rules_ip.site_id
Ref: sites.id < shield_rules_page.site_id
Ref: sites.id < site_imports.site_id
Ref: sites.id - site_memberships.site_id
Ref: sites.id < site_user_preferences.site_id
Ref: sites.id - spike_notifications.site_id
Ref: sites.id - weekly_reports.site_id
Ref: users.id < api_keys.user_id
Ref: users.id < email_activation_codes.user_id
Ref: users.id - enterprise_plans.user_id
Ref: users.id - google_auth.user_id
Ref: users.id < invitations.inviter_id
Ref: users.id < site_imports.imported_by_id
Ref: users.id < site_memberships.user_id
Ref: users.id < site_user_preferences.user_id
Ref: users.id - subscriptions.user_id
Ref: users.id < totp_recovery_codes.user_id